name: deploy-docs

on:
  push:
    branches:
      - main
      - galactic
    tags:
      - "[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  deploy-docs-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: false
          mkdocs-requirements-txt: mkdocs-requirements.txt

  deploy-docs-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: false
          mkdocs-requirements-txt: mkdocs-requirements.txt

  reorder-versions-json:
    needs:
      - deploy-docs-push
      - deploy-docs-workflow-dispatch
    if: |
      always() &&
      (
        needs.deploy-docs-push.result == 'success' ||
        needs.deploy-docs-workflow-dispatch.result == 'success'
      )
    uses: ./.github/workflows/reorder-versions.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
