name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: show info
        run : |
          python3 -V
          echo "======================"
          ros2 pkg list
          echo "======================"

      - name: Install ros2 trace dependent packages
        run : |
          sudo apt update && sudo apt install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt-get install -y ros-galactic-ros2trace
          sudo apt-get install -y ros-galactic-ros2trace-analysis
          sudo apt-get install -y ros-galactic-tracetools
          sudo apt-get install -y ros-galactic-tracetools-analysis
          sudo apt-get install -y ros-galactic-tracetools-launch
          sudo apt-get install -y ros-galactic-tracetools-read
          sudo apt-get install -y ros-galactic-tracetools-test
          sudo apt-get install -y ros-galactic-tracetools-trace
          sudo apt-get install -y ros-galactic-ament-copyright
          # sudo pip install tracetools_analysis
          # sudo pip3 install tracetools_analysis
          source /opt/ros/galactic/setup.sh
        shell: bash
        
      - name: ROSDEP install
        run: |
          sudo apt-get install python3-rosdep
          # sudo rosdep init
          rosdep update
          rosdep install -i --from-paths . -y --rosdistro galactic
          # source /opt/ros/galactic/setup.sh

      - name: Install dependent packages
        run: python3 -m pip install -r requirements.txt

      - name: Run pytest
        run: python3 -m pytest
