name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install ros2 trace dependent packages
        run : |
        sudo apt install -y ros-galactic-ros2trace
        sudo apt install -y ros-galactic-ros2trace-analysis
        sudo apt install -y ros-galactic-tracetools
        sudo apt install -y ros-galactic-tracetools-analysis
        sudo apt install -y ros-galactic-tracetools-launch
        sudo apt install -y ros-galactic-tracetools-read
        sudo apt install -y ros-galactic-tracetools-test
        sudo apt install -y ros-galactic-tracetools-trace

      - name: Install dependent packages
        run: python3 -m pip install -r requirements.txt

      - name: Run pytest
        run: python3 -m pytest