name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install ros2 trace dependent packages
        run : |
          source /opt/ros/galactic/setup.sh
          # sudo apt-get install -y ros-galactic-ros2trace
          # sudo apt-get install -y ros-galactic-ros2trace-analysis
          sudo apt-get install -y ros-galactic-tracetools
          sudo apt-get install -y ros-galactic-tracetools-analysis
          # sudo apt-get install -y ros-galactic-tracetools-launch
          # sudo apt-get install -y ros-galactic-tracetools-read
          # sudo apt-get install -y ros-galactic-tracetools-test
          # sudo apt-get install -y ros-galactic-tracetools-trace
        shell: bash

      - name: Install dependent packages
        run: python3 -m pip install -r requirements.txt

      - name: Run pytest
        run: python3 -m pytest
